### ISSUE TITLE
Headless CMS Recommendations

### ISSUE THREAD

**Issue by derekcoleman** [n370/awesome-headless-cms#6]
Hi,

You have a great list of headless CMS resources. May I suggest a few additional articles that I think will be helpful to your audience?

[Headless CMS: Learn the What, Why, and How](https://buttercms.com/blog/headless-cms-learn-the-what-why-and-how) by @buttercms
[Content as a Service: Your Guide to the What, Why, and How](https://buttercms.com/blog/content-as-a-service-your-guide-to-the-what-why-and-how) by @buttercms

Best,
Derek

**Comment by n370** [comment]
Hey @derekcoleman I appreciate your interest in the project. I've merged your PR but I just came to realize that the second link you have suggested here wasn't there. Feel free to open another PR adding it and I'll be happy to merge it asap. Otherwise, just give me a few days and I can do it myself.

Kind regards,
Dylson

**Comment by derekcoleman** [comment]
Thanks, @n370. I just submitted the new PR with the second link.

**Comment by n370** [comment]
Awesome! Thank you very much.

**Comment by n370** [comment]
#7 #8
